#!/bin/bash

## Description: Imports a local DB dump from the project root.
## Usage: db-import
## Example: "ddev db-import"

vendor/bin/typo3 database:updateschema
vendor/bin/typo3 database:import < var/tmp/deployer-db-dump.sql
vendor/bin/typo3 referenceindex:update
